//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LatypovDinarDemo2025.Databases
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LatypovDinarDemo2025Entities : DbContext
    {
        public LatypovDinarDemo2025Entities()
            : base("name=LatypovDinarDemo2025Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Material> Material { get; set; }
        public DbSet<MaterialType> MaterialType { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<ProductMaterial> ProductMaterial { get; set; }
        public DbSet<ProductType> ProductType { get; set; }
        public DbSet<Supplier> Supplier { get; set; }
        public DbSet<SupplierMaterial> SupplierMaterial { get; set; }
        public DbSet<SupplierType> SupplierType { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Unit> Unit { get; set; }
    }
}
