//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LatypovDinarDemo2025.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductMaterial = new HashSet<ProductMaterial>();
        }
    
        public int Id { get; set; }
        public string Article { get; set; }
        public Nullable<int> IdProductType { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] ImageProduct { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> MassNetto { get; set; }
        public Nullable<decimal> MassBrutto { get; set; }
        public byte[] Sertificate { get; set; }
        public string StandartNumber { get; set; }
        public Nullable<System.TimeSpan> TimeCook { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> NumberWorkshop { get; set; }
        public Nullable<int> CountPeopleForCook { get; set; }
    
        public virtual ProductType ProductType { get; set; }
        public virtual ICollection<ProductMaterial> ProductMaterial { get; set; }
    }
}
