//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LatypovDinarDemo2025.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.SupplierMaterial = new HashSet<SupplierMaterial>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdSupplierType { get; set; }
        public string INN { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    
        public virtual SupplierType SupplierType { get; set; }
        public virtual ICollection<SupplierMaterial> SupplierMaterial { get; set; }
    }
}
